import '@/styles/globals.css'
import Navbar from './Navbar'

export default function App({ Component, pageProps }) {

  return <>
    <Navbar />
    <Component {...pageProps} />
    <p className='mt-5 flex justify-center flex-col p-6'>Auto generated by AI. Proudly built by  <a href="http://anasdew.tech/" target="_blank" rel="noopener noreferrer" className='text-blue-500'>  Anas Dew</a></p> 
  </>
}
